### ISSUE TITLE
Auth: Integration of local IDP 

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#1988]
First iteration of Authentication feature: Ability to provision users/passwords using embedded IDP

Spec: 
Design:

- [x] Using Salt, generate self-signed certificates needed for Dex deployment (#2008)
- [x] Deploy Dex in MetalK8s from the official **Dex Charts** while making use of
- [x] the generated certificates above (#2007)
- [x] Configure Kubernetes API server flags to use Dex (#2010)
- [x] Expose Dex on the control plane using Ingress (#2011)
- [x] Implement MetalK8s UI integration with Dex (#2015)
- [x] Theme the Dex GUI to match MetalK8s UI specs (#2016)
