### ISSUE TITLE
Centos/RHEL8 support

### ISSUE THREAD

**Issue by thomasdanan** [scality/metalk8s#2164]
**Component**:

'all'

**Why this is needed**:

Since centos/RHEL 8 is out since few months now, some users will want to deploy MetalK8s on it.

**What should be done**:

- [x] Adapt Vagrantfile to be able to deploy CentOS / RHEL 8 VMs
- [x] Adapt buildchain to download and build packages for CentOS 8
- [x] Ensure installation / upgrade / downgrade work well
- [x] Add tests in CI
- [x] Update documentation if needs be
- [x] Update CHANGELOG

**Implementation proposal** (strongly recommended):

**Test plan**:
