### ISSUE TITLE
Continuous Integration separation

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#2294]
Currently we only have pre-merge that last longer and longer with not a full test coverage because of this time to merge increasing for each tests added.

Following design document about CI we need to

- [x] Create Nightly post-merge test running on each `development` branches
- [x] Move current upgrade and downgrade test to post-merge
- [x] Generate report from CI test result output
- [x] Have great alerting about post-merge result
- [x] Documentation about how to add new test result in TestRail

**Comment by gdemonet** [comment]
> Generate report from CI test result output

What format? Why? Who generates the report, Eve? Our build stages? This specific point needs some design IMHO

> great alerting about post-merge result

WDYM? What's the deliverable?
